### ISSUE TITLE
Join all channels?

### ISSUE THREAD

**Issue by Linnun** [Inouju/mambo#4]
From the readme:

> channels: List of the channels the bot will join, this can be either a list of channel ids such as [1, 12, 24] or "all" to join all the channels

What do you mean the bot can join multiple or even all channels? As far as I know you can only be in one channel and only listen to the channel chat in one channel via server query.

**Comment by Inouju** [comment]
You are correct: one server query client can only listen to one channel chat at a time.

However, the bot will spawn multiple instances to connect to multiple channels.
